#!/bin/bash

# Logic referenced from:
# https://github.com/buildkite/agent/blob/30f8cc6/bootstrap/bootstrap.go#L1080-L1272

GIT_BRANCH=${BUILDKITE_PLUGIN_CHECKOUT_SPECIFIC_BRANCH_BRANCH:-$BUILDKITE_PIPELINE_DEFAULT_BRANCH}

echo "Checking out branch: $GIT_BRANCH"

if [[ -d ".git" ]]; then
  if git remote get-url origin; then
    git remote set-url origin "$BUILDKITE_REPO"
  else
    git remote add origin "$BUILDKITE_REPO"
  fi;
else
  git clone "$BUILDKITE_REPO" .
fi;

git clean -ffxdq

git fetch -v --prune origin "$GIT_BRANCH"
git checkout -f FETCH_HEAD

git clean -ffxdq

if [ -n "$BUILDKITE_AGENT_ACCESS_TOKEN" ]; then
  echo "Checking to see if Git data needs to be sent to Buildkite"

  if ! buildkite-agent meta-data exists buildkite:git:commit; then
    COMMIT_DATA=$(git --no-pager show HEAD -s --format=fuller --no-color)
    buildkite-agent meta-data set buildkite:git:commit "$COMMIT_DATA"
  fi
fi
