#!/bin/bash

GIT_BRANCH=${BUILDKITE_PLUGIN_CHECKOUT_SPECIFIC_BRANCH_BRANCH:-master}

echo "Checking out branch: $GIT_BRANCH"

if [[ -d ".git" ]]; then
  if git remote get-url origin; then
    git remote set-url origin "$BUILDKITE_REPO"
  else
    git remote add origin "$BUILDKITE_REPO"
  fi;
else
  git clone "$BUILDKITE_REPO" .
fi;

git clean -ffxdq

git fetch -v --prune origin "$GIT_BRANCH"
git checkout -f FETCH_HEAD

git clean -ffxdq
